springdoc:
  swagger-ui:
    path: /swagger-ui.html
#  packages-to-scan: br.com.insannity.transactionBFF.controllers
spring:
  redis:
    port: 6379
    host: localhost
limites:
  url: http://localhost:8081